### ISSUE TITLE
iquest: new function `trunc` or `substr`, to assist construction of bins or histograms

### ISSUE THREAD

**Issue by mcast** [irods/irods#3263]
In #3262 I mention breaking a large number of file-replicas matching some (simple and fast) criteria into bins by `DATA_ID`, so I can perform slower processing upon the chunks.  The construction of window boundaries[1] is slow and rises when the number of windows goes up.

A simple and generally useful way to speed it up would be to add an output function to `iquest`'s SELECT vocabulary to truncate numeric values _e.g._ `trunc('12345678', 3) => '12345000'` or cut pieces out of strings _e.g._ `[substr](http://perldoc.perl.org/functions/substr.html)('12345678', 0, -3) => '12345'`.  Allowing one attribute input and the rest only constants should be sufficient.

This should allow a query like `select trunc(DATA_ID,3), min(DATA_ID), max(DATA_ID), count(DATA_ID) where META_DATA_ATTR_NAME = 'id_ifile'` to produce a list of bins with their sizes, instead of having to run one iquest per bin size measurement _and in the process_ repeat the ATTR_NAME lookups.

Please can we have this one day?

---

[1]
1. Choose target window size `binsize`.  Use tolerance factor `sizetol = 2`
2. `select min(DATA_ID), max(DATA_ID), count(DATA_ID) where $WANTED` to get the range and construct the first bin
3. When a bin contain too many items, split by the midpoint DATA_ID
   - `select min(DATA_ID), max(DATA_ID), count(DATA_ID) where $WANTED and DATA_ID between $min $max` to measure each bin
4. After all windows are small enough, try to merge too-small bins into either the next or previous bin, allowing the result to be up to `binsize*sizetol`

**Comment by trel** [comment]
We are looking to rewrite/replace/refactor GenQuery, and this would be a useful addition.

**Comment by korydraughn** [comment]
It's not clear to me what is being asked. GenQuery2 supports multi-arg/nested functions.

Perhaps this is already solved?

**Comment by trel** [comment]
this works today in postgres...

```
ICAT=> select trunc(123456.78,1);
   trunc   
-----------
 123456.7
(1 row)

ICAT=> select trunc(123456.78,-2);
 trunc  
--------
 123400
(1 row)
```

but `iquery`...

```
$ iquery "select trunc(12345.67,-2)"
error: -167000
$ ierror 167000
irods error: -167000 SYS_LIBRARY_ERROR 
$ tail -n1 /var/log/irods/irods.log | jq
{
  "log_category": "api",
  "log_level": "error",
  "log_message": "rs_genquery2: GenQuery2 error: invalid character: . at position 19",
  "request_api_name": "GENQUERY2_AN",
  "request_api_number": 10221,
  "request_api_version": "d",
  "request_client_user": "rods",
  "request_host": "127.0.0.1",
  "request_proxy_user": "rods",
  "request_release_version": "rods4.3.3",
  "server_host": "xxxxxx",
  "server_pid": 2117698,
  "server_timestamp": "2024-12-16T02:03:17.483Z",
  "server_type": "agent",
  "server_zone": "tempZone"
}
```

and then trying to get rid of the invalid character still failed...

```
$ iquery "select trunc(12345\.67,-2)"
error: -167000
$ tail -n1 /var/log/irods/irods.log | jq
{
  "log_category": "api",
  "log_level": "error",
  "log_message": "rs_genquery2: GenQuery2 error: invalid character: \\ at position 19",
  "request_api_name": "GENQUERY2_AN",
  "request_api_number": 10221,
  "request_api_version": "d",
  "request_client_user": "rods",
  "request_host": "127.0.0.1",
  "request_proxy_user": "rods",
  "request_release_version": "rods4.3.3",
  "server_host": "xxxxxx",
  "server_pid": 2117917,
  "server_timestamp": "2024-12-16T02:05:52.347Z",
  "server_type": "agent",
  "server_zone": "tempZone"
}

$ iquery "select trunc('12345.67',-2)"
error: -130000
$ tail -n1 /var/log/irods/irods.log | jq
{
  "log_category": "api",
  "log_level": "error",
  "log_message": "rs_genquery2: Could not generate SQL from GenQuery.",
  "request_api_name": "GENQUERY2_AN",
  "request_api_number": 10221,
  "request_api_version": "d",
  "request_client_user": "rods",
  "request_host": "127.0.0.1",
  "request_proxy_user": "rods",
  "request_release_version": "rods4.3.3",
  "server_host": "xxxxxx",
  "server_pid": 2117972,
  "server_timestamp": "2024-12-16T02:06:28.360Z",
  "server_type": "agent",
  "server_zone": "tempZone"
}
```

**Comment by korydraughn** [comment]
I think you need to include a GenQuery2 column for it to work.
```
$ iquery "select DATA_NAME, trunc('123456.78', 1)" | jq
[
  [
    "foo",
    "123456.7"
  ]
]
```
```
$ iquery "select DATA_NAME, trunc('123456.78', -2)" | jq
[
  [
    "foo",
    "123400"
  ]
]
```

**Comment by mcast** [comment]
On Sun, Dec 15, 2024 at 03:35:58PM -0800, Kory Draughn wrote:

> It's not clear to me what is being asked.

Hi folks,

I think that was me a long time ago.  I don't know what the team are
doing with the system these days, and I don't have an iRODS system
here to try out commands on.

The bit about "windowing", as I remember, needed this -

On Mon, Dec 16, 2024 at 05:17:37AM -0800, Kory Draughn wrote:

> ```
> $ iquery "select DATA_NAME, trunc('123456.78', -2)" | jq
> [
>   [
>     "foo",
>     "123400"
>   ]
> ]
> ```

but possibly with `trunc(DATA_ID, -2)` or similar, and then a GROUP
BY?

The windows were for selecting a subset of some larger set of files to
operate on so the returned data didn't break stuff or time out.

Here by dropping two sigfigs you're allowing GROUP BY to window the
files into 1% buckets and gather some aggregate stats.


Without further input from those still using it, I would guess if it
can do `select group_by(trunc(DATA_ID, -2)), average(DATA_SIZE)` this
is done?

If it can't do that, it might be done enough / no longer needed?


Keep well,

Matthew

**Comment by korydraughn** [comment]
Thanks for responding.

GenQuery2 does support GROUP BY, but it needs to be expanded to support functions. That should be pretty easy to implement.

**Comment by mcast** [comment]
> GenQuery2 does support GROUP BY, but it needs to be expanded to
> support functions. That should be pretty easy to implement.

OK, well the code I left behind won't use it unless it's updated.
Maybe @kript can advise on whether it's worth your time expanding it?


Keep well,

Matthew

**Comment by korydraughn** [comment]
I've opened #8093.

> Maybe @kript can advise on whether it's worth your time expanding it?

It looks like a trivial enhancement and I think others will find it useful. One of our goals for GenQuery2 is to allow use more access to SQL features, and #8093 aligns with that.

**Comment by korydraughn** [comment]
GenQuery2 supports functions in the GROUP-BY clause since #8093.

There are no plans to add support for `trunc` or `substr` to GenQuery1.

Closing.
