### ISSUE TITLE
file_modified should be called only when data has changed

### ISSUE THREAD

**Issue by bh9** [irods/irods#4099]
- [x] master
- [x] 4-2-stable
- [x] 4-1-stable
-----

4.1.10
```
bh9@irods-sanger1:~$ iput -K thisiswrong
bh9@irods-sanger1:~$ ils -L thisiswrong
  bh9               0 root;replicate;seq-red;red4;irods-seq-i23-fg          373 2018-09-04.15:30 & thisiswrong
    fdc45f5eb8963c5a53b71a00a998839a    generic    /irods-seq-i23-fg/home/bh9#Sanger1/thisiswrong
  bh9               1 root;replicate;seq-green;green5;irods-seq-sr08-fg          373 2018-09-04.15:30 & thisiswrong
    fdc45f5eb8963c5a53b71a00a998839a    generic    /irods-seq-sr08-fg/home/bh9#Sanger1/thisiswrong
#Edit replica 0 on disk (e.g. to emulate corruption)
bh9@irods-sanger1:~$ ils -L thisiswrong
  bh9               0 root;replicate;seq-red;red4;irods-seq-i23-fg          373 2018-09-04.15:30 & thisiswrong
    fdc45f5eb8963c5a53b71a00a998839a    generic    /irods-seq-i23-fg/home/bh9#Sanger1/thisiswrong
  bh9               1 root;replicate;seq-green;green5;irods-seq-sr08-fg          373 2018-09-04.15:30 & thisiswrong
    fdc45f5eb8963c5a53b71a00a998839a    generic    /irods-seq-sr08-fg/home/bh9#Sanger1/thisiswrong
bh9@irods-sanger1:~$ ichksum -Kn 0 thisiswrong
ERROR: chksumDataObjUtil: rcDataObjChksum error for /seq/home/bh9#Sanger1/thisiswrong status = -314000 USER_CHKSUM_MISMATCH
ERROR: chksumUtil: chksum error for /seq/home/bh9#Sanger1/thisiswrong, status = -314000 status = -314000 USER_CHKSUM_MISMATCH
Total checksum performed = 1, Failed checksum = 1
bh9@irods-sanger1:~$ ichksum -Kn 1 thisiswrong
    thisiswrong                       fdc45f5eb8963c5a53b71a00a998839a
Total checksum performed = 1, Failed checksum = 0
bh9@irods-sanger1:~$ ils -L thisiswrong
  bh9               0 root;replicate;seq-red;red4;irods-seq-i23-fg          373 2018-09-04.15:30 & thisiswrong
    fdc45f5eb8963c5a53b71a00a998839a    generic    /irods-seq-i23-fg/home/bh9#Sanger1/thisiswrong
  bh9               1 root;replicate;seq-green;green5;irods-seq-sr08-fg          373 2018-09-04.15:30 & thisiswrong
    fdc45f5eb8963c5a53b71a00a998839a    generic    /irods-seq-sr08-fg/home/bh9#Sanger1/thisiswrong
bh9@irods-sanger1:~$ ichksum -fn 0 thisiswrong
    thisiswrong                       6f96f268ee7c52cdd2c940201e48e649
Total checksum performed = 1, Failed checksum = 0
bh9@irods-sanger1:~$ ichksum -fn 1 thisiswrong
    thisiswrong                       fdc45f5eb8963c5a53b71a00a998839a
Total checksum performed = 1, Failed checksum = 0
bh9@irods-sanger1:~$ ils -L thisiswrong
  bh9               0 root;replicate;seq-red;red4;irods-seq-i23-fg          373 2018-09-04.15:30 & thisiswrong
    6f96f268ee7c52cdd2c940201e48e649    generic    /irods-seq-i23-fg/home/bh9#Sanger1/thisiswrong
  bh9               1 root;replicate;seq-green;green5;irods-seq-sr08-fg          373 2018-09-04.15:30 & thisiswrong
    fdc45f5eb8963c5a53b71a00a998839a    generic    /irods-seq-sr08-fg/home/bh9#Sanger1/thisiswrong
bh9@irods-sanger1:~$ ichksum -fa thisiswrong
ERROR: chksumDataObjUtil: rcDataObjChksum error for /seq/home/bh9#Sanger1/thisiswrong status = -27000 SYS_COPY_LEN_ERR
ERROR: chksumUtil: chksum error for /seq/home/bh9#Sanger1/thisiswrong, status = -27000 status = -27000 SYS_COPY_LEN_ERR
Total checksum performed = 1, Failed checksum = 1
bh9@irods-sanger1:~$ ils -L thisiswrong
  bh9               0 root;replicate;seq-red;red4;irods-seq-i23-fg          373 2018-09-04.15:30 & thisiswrong
    6f96f268ee7c52cdd2c940201e48e649    generic    /irods-seq-i23-fg/home/bh9#Sanger1/thisiswrong
  bh9               1 root;replicate;seq-green;green5;irods-seq-sr08-fg          373 2018-09-04.15:30 & thisiswrong
    fdc45f5eb8963c5a53b71a00a998839a    generic    /irods-seq-sr08-fg/home/bh9#Sanger1/thisiswrong
bh9@irods-sanger1:~$ ichksum -Kn 1 thisiswrong
ERROR: chksumDataObjUtil: rcDataObjChksum error for /seq/home/bh9#Sanger1/thisiswrong status = -314000 USER_CHKSUM_MISMATCH
ERROR: chksumUtil: chksum error for /seq/home/bh9#Sanger1/thisiswrong, status = -314000 status = -314000 USER_CHKSUM_MISMATCH
Total checksum performed = 1, Failed checksum = 1
bh9@irods-sanger1:~$ ichksum -Kn 0 thisiswrong
    thisiswrong                       6f96f268ee7c52cdd2c940201e48e649
Total checksum performed = 1, Failed checksum = 0
bh9@irods-sanger1:~$ ils -L thisiswrong
  bh9               0 root;replicate;seq-red;red4;irods-seq-i23-fg          373 2018-09-04.15:30 & thisiswrong
    6f96f268ee7c52cdd2c940201e48e649    generic    /irods-seq-i23-fg/home/bh9#Sanger1/thisiswrong
  bh9               1 root;replicate;seq-green;green5;irods-seq-sr08-fg          373 2018-09-04.15:30 & thisiswrong
    fdc45f5eb8963c5a53b71a00a998839a    generic    /irods-seq-sr08-fg/home/bh9#Sanger1/thisiswrong
bh9@irods-sanger1:~$ ichksum -fn 0 thisiswrong
    thisiswrong                       6f96f268ee7c52cdd2c940201e48e649
Total checksum performed = 1, Failed checksum = 0
bh9@irods-sanger1:~$ ichksum -fn 1 thisiswrong
    thisiswrong                       6f96f268ee7c52cdd2c940201e48e649
Total checksum performed = 1, Failed checksum = 0
bh9@irods-sanger1:~$ ils -L thisiswrong
  bh9               0 root;replicate;seq-red;red4;irods-seq-i23-fg          373 2018-09-04.15:30 & thisiswrong
    6f96f268ee7c52cdd2c940201e48e649    generic    /irods-seq-i23-fg/home/bh9#Sanger1/thisiswrong
  bh9               1 root;replicate;seq-green;green5;irods-seq-sr08-fg          373 2018-09-04.15:30 & thisiswrong
    6f96f268ee7c52cdd2c940201e48e649    generic    /irods-seq-sr08-fg/home/bh9#Sanger1/thisiswrong
bh9@irods-sanger1:~$ 
```
Here, using only ichksum, and a manually edited or corrupted replica 0 we are able to change replica 1 to match replica 0, despite replica 1 being correct and matching it's own checksum. We start by editing or corrupting replica 0, thus making it a bad replica. `ichksum -fn 0 thisiswrong` means irods doesn't notice this, and when `ichksum -fa thisiswrong` is called, simply decided that replica 0 is correct, and overwrites replica 1 with replica 0. 
This is fixed in 4.1.12, but shouldn't have been the case in the first place and begs the further question: Is anything else choosing between 2+ replicas with different checksums which are all deemed "correct" by irods?

**Comment by bh9** [comment]
May be the same problem as #4085 (which is 4.2.3)

**Comment by kript** [comment]
👍 NB @bh9 is our newest recruit at Sanger, so is a `consortium member`. 
Also, this has actually corrupted live data for us, so... 🙀

**Comment by trel** [comment]
Definitely, if more than one replica is marked 'good' in the catalog (but are not actually good), then you could be sending/receiving incorrect data elsewhere in your system.  The catalog is the 'Truth', so everything else downstream depends on it.

However, I have just tried to replicate the series of commands above and cannot reproduce the incorrect overwrite with version 4.1.10 or 4.1.11.

setup replication and checksummed file:
```
irods@host:~$ ienv | grep Version
NOTICE: Release Version = rods4.1.10, API Version = d
irods@host:~$ ilsresc
demoResc
repl:replication
├── ufs1
└── ufs2
irods@host:~$ iput -R repl -K VERSION.json bar
irods@host:~$ ils -L bar
  rods              0 repl;ufs2          476 2018-09-10.08:50 & bar
    sha2:r68FlFaqVfjFb7fOtl9VUO/yyP/NeERCS3X3euw4+Dg=    generic    /tmp/ufs2Vault/home/rods/bar
  rods              1 repl;ufs1          476 2018-09-10.08:50 & bar
    sha2:r68FlFaqVfjFb7fOtl9VUO/yyP/NeERCS3X3euw4+Dg=    generic    /tmp/ufs1Vault/home/rods/bar
```

corrupt the on-disk replica 0:
```
irods@host:~$ echo "asfasdfafd" >> /tmp/ufs2Vault/home/rods/bar 
irods@host:~$ ichksum -fn 0 bar
    bar                               sha2:5UhmOuu3SbcOXiODhO3eYQaOKeU9PQq4qeyLw1ZqHLw=
Total checksum performed = 1, Failed checksum = 0
irods@host:~$ ils -L bar
  rods              0 repl;ufs2          476 2018-09-10.08:50 & bar
    sha2:5UhmOuu3SbcOXiODhO3eYQaOKeU9PQq4qeyLw1ZqHLw=    generic    /tmp/ufs2Vault/home/rods/bar
  rods              1 repl;ufs1          476 2018-09-10.08:50 & bar
    sha2:r68FlFaqVfjFb7fOtl9VUO/yyP/NeERCS3X3euw4+Dg=    generic    /tmp/ufs1Vault/home/rods/bar
```

try to reproduce the incorrect overwrite of replica 1 via `ichksum` only:
```
irods@host:~$ ichksum -fn 1 bar
    bar                               sha2:r68FlFaqVfjFb7fOtl9VUO/yyP/NeERCS3X3euw4+Dg=
Total checksum performed = 1, Failed checksum = 0
irods@host:~$ ils -L bar
  rods              0 repl;ufs2          476 2018-09-10.08:50 & bar
    sha2:5UhmOuu3SbcOXiODhO3eYQaOKeU9PQq4qeyLw1ZqHLw=    generic    /tmp/ufs2Vault/home/rods/bar
  rods              1 repl;ufs1          476 2018-09-10.08:50 & bar
    sha2:r68FlFaqVfjFb7fOtl9VUO/yyP/NeERCS3X3euw4+Dg=    generic    /tmp/ufs1Vault/home/rods/bar
irods@host:~$ ichksum -fa bar
ERROR: chksumDataObjUtil: rcDataObjChksum error for /tempZone/home/rods/bar status = -314000 USER_CHKSUM_MISMATCH
ERROR: chksumUtil: chksum error for /tempZone/home/rods/bar, status = -314000 status = -314000 USER_CHKSUM_MISMATCH
Total checksum performed = 1, Failed checksum = 1
Level 0: [-]    irods_create_write_replicator.cpp:64:replicate :  status [USER_CHKSUM_MISMATCH]  errno [] -- message [Failed to replicate the data object: "/tempZone/home/rods/bar" from resource: "repl;ufs2" to sibling: "repl;ufs1" - USER_CHKSUM_MISMATCH .]
```

the two replicas still report as 'good', but with different checksums (so the system still recognized that the contents are different):
```
irods@host:~$ ils -L bar
  rods              0 repl;ufs2          476 2018-09-10.08:50 & bar
    sha2:5UhmOuu3SbcOXiODhO3eYQaOKeU9PQq4qeyLw1ZqHLw=    generic    /tmp/ufs2Vault/home/rods/bar
  rods              1 repl;ufs1          476 2018-09-10.08:50 & bar
    sha2:r68FlFaqVfjFb7fOtl9VUO/yyP/NeERCS3X3euw4+Dg=    generic    /tmp/ufs1Vault/home/rods/bar
irods@host:~$ ichksum -Kn 1 bar
    bar                               sha2:r68FlFaqVfjFb7fOtl9VUO/yyP/NeERCS3X3euw4+Dg=
Total checksum performed = 1, Failed checksum = 0
irods@host:~$ ichksum -Kn 0 bar
    bar                               sha2:5UhmOuu3SbcOXiODhO3eYQaOKeU9PQq4qeyLw1ZqHLw=
Total checksum performed = 1, Failed checksum = 0
irods@host:~$ ils -L bar
  rods              0 repl;ufs2          476 2018-09-10.08:50 & bar
    sha2:5UhmOuu3SbcOXiODhO3eYQaOKeU9PQq4qeyLw1ZqHLw=    generic    /tmp/ufs2Vault/home/rods/bar
  rods              1 repl;ufs1          476 2018-09-10.08:50 & bar
    sha2:r68FlFaqVfjFb7fOtl9VUO/yyP/NeERCS3X3euw4+Dg=    generic    /tmp/ufs1Vault/home/rods/bar
irods@host:~$ ichksum -fn 0 bar
    bar                               sha2:5UhmOuu3SbcOXiODhO3eYQaOKeU9PQq4qeyLw1ZqHLw=
Total checksum performed = 1, Failed checksum = 0
irods@host:~$ ichksum -fn 1 bar
    bar                               sha2:r68FlFaqVfjFb7fOtl9VUO/yyP/NeERCS3X3euw4+Dg=
Total checksum performed = 1, Failed checksum = 0
irods@host:~$ ils -L bar
  rods              0 repl;ufs2          476 2018-09-10.08:50 & bar
    sha2:5UhmOuu3SbcOXiODhO3eYQaOKeU9PQq4qeyLw1ZqHLw=    generic    /tmp/ufs2Vault/home/rods/bar
  rods              1 repl;ufs1          476 2018-09-10.08:50 & bar
    sha2:r68FlFaqVfjFb7fOtl9VUO/yyP/NeERCS3X3euw4+Dg=    generic    /tmp/ufs1Vault/home/rods/bar
```

I upgraded to 4.1.11 in place and tried again:
```
irods@host:~$ ienv | grep Version
NOTICE: Release Version = rods4.1.11, API Version = d
irods@host:~$ ils -L bar
  rods              0 repl;ufs2          476 2018-09-10.08:50 & bar
    sha2:5UhmOuu3SbcOXiODhO3eYQaOKeU9PQq4qeyLw1ZqHLw=    generic    /tmp/ufs2Vault/home/rods/bar
  rods              1 repl;ufs1          476 2018-09-10.08:50 & bar
    sha2:r68FlFaqVfjFb7fOtl9VUO/yyP/NeERCS3X3euw4+Dg=    generic    /tmp/ufs1Vault/home/rods/bar
irods@host:~$ ichksum -fa bar
ERROR: chksumDataObjUtil: rcDataObjChksum error for /tempZone/home/rods/bar status = -314000 USER_CHKSUM_MISMATCH
Level 0: [-]    irods_create_write_replicator.cpp:64:replicate :  status [USER_CHKSUM_MISMATCH]  errno [] -- message [Failed to replicate the data object: "/tempZone/home/rods/bar" from resource: "repl;ufs2" to sibling: "repl;ufs1" - USER_CHKSUM_MISMATCH .]


ERROR: chksumUtil: chksum error for /tempZone/home/rods/bar, status = -314000 status = -314000 USER_CHKSUM_MISMATCH
Total checksum performed = 1, Failed checksum = 1
irods@host:~$ ils -L bar
  rods              0 repl;ufs2          476 2018-09-10.08:50 & bar
    sha2:5UhmOuu3SbcOXiODhO3eYQaOKeU9PQq4qeyLw1ZqHLw=    generic    /tmp/ufs2Vault/home/rods/bar
  rods              1 repl;ufs1          476 2018-09-10.08:50 & bar
    sha2:r68FlFaqVfjFb7fOtl9VUO/yyP/NeERCS3X3euw4+Dg=    generic    /tmp/ufs1Vault/home/rods/bar
irods@host:~$ ichksum -Kn 1 bar
    bar                               sha2:r68FlFaqVfjFb7fOtl9VUO/yyP/NeERCS3X3euw4+Dg=
Total checksum performed = 1, Failed checksum = 0
irods@host:~$ ichksum -Kn 0 bar
    bar                               sha2:5UhmOuu3SbcOXiODhO3eYQaOKeU9PQq4qeyLw1ZqHLw=
Total checksum performed = 1, Failed checksum = 0
irods@host:~$ ils -L bar
  rods              0 repl;ufs2          476 2018-09-10.08:50 & bar
    sha2:5UhmOuu3SbcOXiODhO3eYQaOKeU9PQq4qeyLw1ZqHLw=    generic    /tmp/ufs2Vault/home/rods/bar
  rods              1 repl;ufs1          476 2018-09-10.08:50 & bar
    sha2:r68FlFaqVfjFb7fOtl9VUO/yyP/NeERCS3X3euw4+Dg=    generic    /tmp/ufs1Vault/home/rods/bar
irods@host:~$ ichksum -fn 0 bar
    bar                               sha2:5UhmOuu3SbcOXiODhO3eYQaOKeU9PQq4qeyLw1ZqHLw=
Total checksum performed = 1, Failed checksum = 0
irods@host:~$ ichksum -fn 1 bar
    bar                               sha2:r68FlFaqVfjFb7fOtl9VUO/yyP/NeERCS3X3euw4+Dg=
Total checksum performed = 1, Failed checksum = 0
irods@host:~$ ils -L bar
  rods              0 repl;ufs2          476 2018-09-10.08:50 & bar
    sha2:5UhmOuu3SbcOXiODhO3eYQaOKeU9PQq4qeyLw1ZqHLw=    generic    /tmp/ufs2Vault/home/rods/bar
  rods              1 repl;ufs1          476 2018-09-10.08:50 & bar
    sha2:r68FlFaqVfjFb7fOtl9VUO/yyP/NeERCS3X3euw4+Dg=    generic    /tmp/ufs1Vault/home/rods/bar
```

**Comment by bh9** [comment]
rodsuser vs rodsadmin?

**Comment by trel** [comment]
I have just tried again as a rodsuser, but could not reproduce the overwrite on a fresh 4.1.10 installation and a data object under a replication resource.

**Comment by bh9** [comment]
There's an strace of it overwriting the file in @kript's RENCI_Upload drive in the "ichksum overwrite bug hunt #4099" folder

**Comment by bh9** [comment]
What's also interesting is that it doesn't always write the entire change to the file. Adding a few (<5) characters to the end of replica 0 results in just the first being added to replica 1

**Comment by bh9** [comment]
My 2-node deploy (1 iCAT w. resource and 1 resource) reproduced the issue, 
```
ubuntu@bh9-irods-test2:~$ ils -L irodsscript.sh
  rods              0 repl;demoResc         1219 2018-09-12.13:26 & irodsscript.sh
    sha2:9YeQY4GtF2D8dmXgUN0KYO7yohT50nx1c0DGa4glreo=    generic    /var/lib/irods/iRODS/Vault/home/rods/irodsscript.sh
  rods              1 repl;bh9-irods-test2Resource         1219 2018-09-12.13:26 & irodsscript.sh
    sha2:9YeQY4GtF2D8dmXgUN0KYO7yohT50nx1c0DGa4glreo=    generic    /var/lib/irods/iRODS/Vault/home/rods/irodsscript.sh

ubuntu@bh9-irods-test2:~$ ichksum -fn0 irodsscript.sh    irodsscript.sh                    sha2:YbIOIXVDTN/12LkWLZz09JCgs3ezyNaxsW0uYly//9c=
Total checksum performed = 1, Failed checksum = 0
ubuntu@bh9-irods-test2:~$ ils -L irodsscript.sh
  rods              0 repl;demoResc         1219 2018-09-12.13:26 & irodsscript.sh
    sha2:YbIOIXVDTN/12LkWLZz09JCgs3ezyNaxsW0uYly//9c=    generic    /var/lib/irods/iRODS/Vault/home/rods/irodsscript.sh
  rods              1 repl;bh9-irods-test2Resource         1219 2018-09-12.13:26 & irodsscript.sh
    sha2:9YeQY4GtF2D8dmXgUN0KYO7yohT50nx1c0DGa4glreo=    generic    /var/lib/irods/iRODS/Vault/home/rods/irodsscript.sh
ubuntu@bh9-irods-test2:~$ ichksum -fa irodsscript.sh
    irodsscript.sh                    sha2:YbIOIXVDTN/12LkWLZz09JCgs3ezyNaxsW0uYly//9c=
Total checksum performed = 1, Failed checksum = 0
ubuntu@bh9-irods-test2:~$ ils -L irodsscript.sh
  rods              0 repl;demoResc         1219 2018-09-12.13:26 & irodsscript.sh
    sha2:YbIOIXVDTN/12LkWLZz09JCgs3ezyNaxsW0uYly//9c=    generic    /var/lib/irods/iRODS/Vault/home/rods/irodsscript.sh
  rods              1 repl;bh9-irods-test2Resource         1219 2018-09-12.14:05 & irodsscript.sh
    sha2:YbIOIXVDTN/12LkWLZz09JCgs3ezyNaxsW0uYly//9c=    generic    /var/lib/irods/iRODS/Vault/home/rods/irodsscript.sh
ubuntu@bh9-irods-test2:~$ ichksum -fn1 irodsscript.sh
    irodsscript.sh                    sha2:YbIOIXVDTN/12LkWLZz09JCgs3ezyNaxsW0uYly//9c=
Total checksum performed = 1, Failed checksum = 0
ubuntu@bh9-irods-test2:~$ ils -L irodsscript.sh
  rods              0 repl;demoResc         1219 2018-09-12.13:26 & irodsscript.sh
    sha2:YbIOIXVDTN/12LkWLZz09JCgs3ezyNaxsW0uYly//9c=    generic    /var/lib/irods/iRODS/Vault/home/rods/irodsscript.sh
  rods              1 repl;bh9-irods-test2Resource         1219 2018-09-12.14:05 & irodsscript.sh
    sha2:YbIOIXVDTN/12LkWLZz09JCgs3ezyNaxsW0uYly//9c=    generic    /var/lib/irods/iRODS/Vault/home/rods/irodsscript.sh
```

**Comment by bh9** [comment]
I've added a file to the shared drive containing the full list of commands run on a pair of vanilla 14.04 openstack VMs to reproduce the issue.

**Comment by trel** [comment]
Got it - looking.

**Comment by trel** [comment]
Something is afoot...

Two machines here - did not reproduce the problem...

Executed the `node1` commands first, then the `node2` commands.


node1 (icat server):
```
irods@vm1:~ $ ienv | grep Version
NOTICE: Release Version = rods4.1.10, API Version = d

irods@vm1:~ $ ilsresc
demoResc
repl:replication
├── ufs1
└── ufs2

irods@vm1:~ $ iput -K -R repl .viminfo foo; ils -L foo                                                                                                                                
  rods              0 repl;ufs1        13275 2018-09-12.14:49 & foo
    de142f828d48ee910fe3b083e9085642    generic    /tmp/ufs1Vault/home/rods/foo
  rods              1 repl;ufs2        13275 2018-09-12.14:49 & foo
    de142f828d48ee910fe3b083e9085642    generic    /tmp/ufs2Vault/home/rods/foo

irods@vm1:~ $ sudo su - irods -c "echo asdfasdfasdf > /tmp/ufs1Vault/home/rods/foo"; sudo ls -l /tmp/ufs1Vault/home/rods/foo                                                          
-rw------- 1 irods irods 13 Sep 12 14:49 /tmp/ufs1Vault/home/rods/foo
```

node2 (resource server):
```
irods@vm2:~$ ils -L foo
  rods              0 repl;ufs1        13275 2018-09-12.14:49 & foo
    de142f828d48ee910fe3b083e9085642    generic    /tmp/ufs1Vault/home/rods/foo
  rods              1 repl;ufs2        13275 2018-09-12.14:49 & foo
    de142f828d48ee910fe3b083e9085642    generic    /tmp/ufs2Vault/home/rods/foo

irods@vm2:~$ ichksum -fn 0 foo; ils -L foo
    foo                               e8b19da37825a3056e84c522f05efce0
Total checksum performed = 1, Failed checksum = 0
  rods              0 repl;ufs1        13275 2018-09-12.14:49 & foo
    e8b19da37825a3056e84c522f05efce0    generic    /tmp/ufs1Vault/home/rods/foo
  rods              1 repl;ufs2        13275 2018-09-12.14:49 & foo
    de142f828d48ee910fe3b083e9085642    generic    /tmp/ufs2Vault/home/rods/foo

irods@vm2:~$ ichksum -fa foo; ils -L foo
    foo                               e8b19da37825a3056e84c522f05efce0
Total checksum performed = 1, Failed checksum = 0
  rods              0 repl;ufs1        13275 2018-09-12.15:00 & foo
    de142f828d48ee910fe3b083e9085642    generic    /tmp/ufs1Vault/home/rods/foo
  rods              1 repl;ufs2        13275 2018-09-12.14:49 & foo
    de142f828d48ee910fe3b083e9085642    generic    /tmp/ufs2Vault/home/rods/foo

irods@vm2:~$ ichksum -fn 1 foo; ils -L foo
    foo                               de142f828d48ee910fe3b083e9085642
Total checksum performed = 1, Failed checksum = 0
  rods              0 repl;ufs1        13275 2018-09-12.15:00 & foo
    de142f828d48ee910fe3b083e9085642    generic    /tmp/ufs1Vault/home/rods/foo
  rods              1 repl;ufs2        13275 2018-09-12.14:49 & foo
    de142f828d48ee910fe3b083e9085642    generic    /tmp/ufs2Vault/home/rods/foo

irods@vm2:~$ ls -l /tmp/ufs2Vault/home/rods/foo
-rw------- 1 irods irods 13275 Sep 12 14:49 /tmp/ufs2Vault/home/rods/foo
```

**Comment by bh9** [comment]
Could you try an edit which doesn't change the length? It occurs to me that you're just adding to the end, and irods may just be writing the amount it thinks it should have, which is just the original file

**Comment by bh9** [comment]
Your example has reproduced, but by overwriting replica 0, back to the original. `2018-09-12.15:00 != 2018-09-12.14:49`

**Comment by bh9** [comment]
When it fails to update the timestamp, it throws `SYS_COPY_LEN_ERR`, but with more debugging on, throws 
```
ERROR: chksumDataObjUtil: rcDataObjChksum error for /tempZone/home/rods/thing status = -27000 SYS_COPY_LEN_ERR
ERROR: chksumUtil: chksum error for /tempZone/home/rods/thing, status = -27000 status = -27000 SYS_COPY_LEN_ERR
Total checksum performed = 1, Failed checksum = 1
Level 0: [-]	irods_create_write_replicator.cpp:64:replicate :  status [SYS_COPY_LEN_ERR]  errno [] -- message [Failed to replicate the data object: "/tempZone/home/rods/thing" from resource: "repl;demoResc" to sibling: "repl;bh9-irods-test2Resource" - SYS_COPY_LEN_ERR .]
```

**Comment by trel** [comment]
I don't think I've reproduced the corruption of replica 1.

Yes, the replica timestamp in the catalog was updated because the replica that was found to be out-of-line (replica 0) was overwritten, correctly, with the original data.

I replayed the same two-node setup, but used `sed` to make a same-length edit:
```
irods@vm1:~ $ echo "aaaa" > foo

irods@vm1:~ $ iput -K -R repl foo; ils -L foo                                                                                                                          
  rods              0 repl;ufs1            5 2018-09-13.12:25 & foo
    e5828c564f71fea3a12dde8bd5d27063    generic    /tmp/ufs1Vault/home/rods/foo
  rods              1 repl;ufs2            5 2018-09-13.12:25 & foo
    e5828c564f71fea3a12dde8bd5d27063    generic    /tmp/ufs2Vault/home/rods/foo

irods@vm1:~ $ cat /tmp/ufs1Vault/home/rods/foo
aaaa
irods@vm1:~ $ sed -i 's/a/b/g' /tmp/ufs1Vault/home/rods/foo
irods@vm1:~ $ cat /tmp/ufs1Vault/home/rods/foo
bbbb

irods@vm1:~ $ ls -l /tmp/ufs1Vault/home/rods/foo                                                                                                                  
-rw------- 1 irods irods 5 Sep 13 12:27 /tmp/ufs1Vault/home/rods/foo
```

After the same `ichksum -fa` calls... the original content of replica 0 was restored:
```
irods@vm1:~ $ cat /tmp/ufs1Vault/home/rods/foo
aaaa
```


Can you explain more about what you mean by...
> "When it fails to update the timestamp,"

**Comment by bh9** [comment]
How did it decide replica 0 was the bad replica? Both were marked as good the whole time. Also, my understanding of ichksum is that it shouldn't change the underlying data *at all*, instead only changing the catalog entry

When the file is changed by an icommand, the catalog timestamp should also change. This is correct behaviour (assuming the icommand is supposed to change data), but in production (and occasionally on the 2-node), the timestamp is not modified. This is probably a different but related issue

**Comment by bh9** [comment]
Do you have a flowchart of what you think ichksum should do?

**Comment by trel** [comment]
I see your question now... Agreed.   I'm not sure why replica 0 was being repaved in my case, and your replica 1 was seen being repaved.  Or how the code is determining which is 'correct', since the catalog has two checksums and both are marked good (&). (I suspect it's just the ordering coming out of the database, aka not ordered).

`ichksum` should not be updating data on disk at all.  It should calculate and record checksums, and complain loudly if it sees inconsistencies.  I believe this is due to the 'file_modified' flag and now has a changed/incorrect behavior from the 'before-times', in this regard.

I do not have a flowchart.

**Comment by trel** [comment]
Looks suspiciously like https://github.com/irods/irods/issues/3525 which was fixed in 4.2.2.

But then, https://github.com/irods/irods/issues/4085 (happening in 4.2.x) must be a bit different.

**Comment by alanking** [comment]
I was able to reproduce the data corruption in 4.1.10 and 4.1.11 with `ichksum`.

#3525 only fixes the replication resource. This fix was brought in via #3436 for 4.1.12, which is why this is fixed on the dev environment. #4085 has to do with the compound resource, so the linked fix would not affect that.

We are looking into an architectural change to prevent triggering a file_modified operation in `rsModDataObjMeta` based on the presence or absence of certain keywords:
https://github.com/irods/irods/blob/b1395000b96aa231c9fd98853f5ad71630555396/server/api/src/rsModDataObjMeta.cpp#L61
This should address the problem for all resource types.

**Comment by alanking** [comment]
Looking into this further, #3436 did not resolve this issue in 4.1, but #3909.

This issue has to do with the way that hierarchy resolution is done in the replication resource. In the past, two "votes" were taken to determine the "selected hierarchy" and the "child list". The first vote was for create/write operations, regardless of what operation was triggering the hierarchy resolution. When this vote is taken, a write operation is pushed onto the "object list" (which is really just an operation list).

Later, when the checksum completes and the file is closed, file_modified is triggered and we come back to `replFileModified`. We check to see if there is any replication to be done, which is really checking to see if anything is in the object list. Seeing as the write/create vote put something in the list, replication is triggered, even though `ichksum` is an open/read/close.

Since the vote now only occurs for the operation in question (instead of one for write/create and one for the operation), nothing is put onto the object list, which is why replication is not triggered.

Hopefully that explanation gives a picture as to what happened between 4.1.10 and 4.1.12. The general fix proposed in my previous comment is still the direction we intend to go.
