### ISSUE TITLE
'imv collA/foo collB/foo' silently fails if collB doesn't exist

### ISSUE THREAD

**Issue by d-w-moore** [irods/irods#4414]
- [x] master
- [x] 4-2-stable
----

### iRODS Version, OS and Version
iRODS : release 4.2.5 and on `master` branch
OS: Ubuntu 16

### What did you try to do?

Use the `imv`  icommand to rename a path (with the collection element of the target path not previously in existence).

### Expected behavior

`imv` should fail (because the target collection doesn't exist), emit an error message to the console, and return a non-zero error code.
### Observed behavior (including steps to reproduce, if applicable)

imv does indeed fail, but returns a success error code (0) to the Unix shell and does not emit an error message to the console.
```
irods@home$ ils
/tempZone/home/rods:
irods@home$  echo abc >x.dat
irods@home$  imkdir test1
irods@home$  imkdir test1/subcoll
irods@home$  iput x.dat test1
irods@home$  ils test1
/tempZone/home/rods/test1:
  x.dat
  C- /tempZone/home/rods/test1/subcoll
irods@home$  ils test2
remote addresses: 127.0.1.1 ERROR: lsUtil: srcPath /tempZone/home/rods/test2 does not exist or user lacks access permission
irods@home$  imv test1/subcoll test2/subcoll
irods@home$ echo $?
0
irods@home$ imv test1/x.dat test2/x.dat
irods@home $ echo $?
0
irods@home$ $ ils test2
remote addresses: 127.0.1.1 ERROR: lsUtil: srcPath /tempZone/home/rods/test2 does not exist or user lacks access permission
irods@home$ $ ils test1
/tempZone/home/rods/test1:
  x.dat
  C- /tempZone/home/rods/test1/subcoll
irods@home$ 
```

As expected (see last command in session above), the objects which failed to be moved are still located in `test1`, where they were created.

Also noted: both of the above attempts to move/rename a path element generate the following text in the rodsLog, while as mentioned the `imv` command itself is silently failing on the console.

```
May 30 20:40:54 pid:10295 remote addresses: 127.0.0.1 ERROR: _rsDataObjRename: dest coll /tempZone/home/rods/test2 does not exist, status = -808000
```

**Comment by trel** [comment]
Very similar, but different from #4117 (which was fixed in 4.1.12).

Confirmed this was a bug in 4.1.12:

```
$ imiscsvrinfo | grep relVersion
relVersion=rods4.1.12
$ ils -r
/tempZone/home/rods:
  C- /tempZone/home/rods/a
/tempZone/home/rods/a:
  C- /tempZone/home/rods/a/b
/tempZone/home/rods/a/b:
  C- /tempZone/home/rods/a/b/c
/tempZone/home/rods/a/b/c:
  file
$ imv a/b g/b
$ echo $?
0
$ ils -r
/tempZone/home/rods:
  C- /tempZone/home/rods/a
/tempZone/home/rods/a:
  C- /tempZone/home/rods/a/b
/tempZone/home/rods/a/b:
  C- /tempZone/home/rods/a/b/c
/tempZone/home/rods/a/b/c:
  file
$ tail -n50 /var/lib/irods/iRODS/server/log/rodsLog.2019.05.26 | grep -C1 ERROR
May 30 21:33:29 pid:28990 NOTICE: Agent process 26082 started for puser=rods and cuser=rods from 127.0.0.1
May 30 21:33:29 pid:26082 ERROR: _rsDataObjRename: dest coll /tempZone/home/rods/g does not exist, status = -808000
May 30 21:33:29 pid:26082 NOTICE: readAndProcClientMsg: received disconnect msg from client
```

**Comment by mcast** [comment]
I believe this bug is the same as #4117, which is still broken in 4.1.12 .

**Comment by d-w-moore** [comment]
I think this issue is actually distinct from [#4117](https://github.com/irods/irods/issues/4117), which appears to have been fixed before 4.2.6 : 
```
irods@canute:~$ imv a/b a/z
irods@canute:~$ ils a/z/c/x.x
  /tempZone/home/rods/a/z/c/x.x
```
O.t.o.h. when the target of the move is just *subordinate to* a path element not yet existing, we have the issue #4414 described above, but put in terms of this example, we can demo it in 4.2.6 thus:
```
$ imv a/b a/z/b  # -> zero error code (success) returned
irods@canute:~$ ils a/b/c/x.x
  /tempZone/home/rods/a/b/c/x.x
irods@canute:~$ 
irods@canute:~$ ils a/z/b
remote addresses: 152.54.8.225 ERROR: lsUtil: srcPath /tempZone/home/rods/a/z/b does not exist or user lacks access permission
```
... apparently still an issue.

**Comment by d-w-moore** [comment]
I now have to go back on my statement of yesterday.  I agree with mcast's statement that this issue does in fact appear  to be one-in-the-same with [#4117](https://github.com/irods/irods/issues/4117) .  I'd been thrown by the original problem statement in 4117 , which I now believe mistakenly posited the example of `imv a/b a/z` as provoking the issue (though that command actually succeeds in all versions of iRODS I've tested  - 4.1.11 and 12, 4.2.6 and the current master branch) rather than `imv a/b a/z/b` which silently fails in all of those iRODS versions.
