### ISSUE TITLE
cyberduck and irods file transfer

### ISSUE THREAD

**Issue by a-tsygan** [irods/irods#5780]
Recently we've upgraded to 4.2.11 and during tests of a copy file (size ~12Gb) over cyberduck we see: 
Aug 19 11:36:19 pid:9087 remote addresses: 129.125.77.67 ERROR: [-]	/irods/lib/core/src/apiHandler.cpp:198:irods::error irods::init_api_table(irods::api_entry_table &, irods::pack_entry_table &, bool) :  status [PLUGIN_ERROR]  errno [] -- message [failed to open shared object file [/usr/lib/irods/plugins/api/libirods_data_object_modify_info_server.so] :: dlerror: is [/usr/lib/irods/plugins/api/libirods_data_object_modify_info_server.so: failed to map segment from shared object: Cannot allocate memory]]
	[-]	/irods/lib/core/include/irods_load_plugin.hpp:176:irods::error irods::load_plugin(PluginType *&, const std::string &, const std::string &, const std::string &, const Ts &...) [PluginType = irods::api_entry, Ts = <char [12]>] :  status [PLUGIN_ERROR]  errno [] -- message [failed to open shared object file [/usr/lib/irods/plugins/api/libirods_data_object_modify_info_server.so] :: dlerror: is [/usr/lib/irods/plugins/api/libirods_data_object_modify_info_server.so: failed to map segment from shared object: Cannot allocate memory]]

WebDav and icommands seams to work fine. Cyberduck uses Java (Jargon). I suspect that there are some server side Linux parameters that must be set correctly per process to avoid memory overuse. 
Are there any general gidlines? Any expected shmmax, min values or swap size?    

However on version 4.2.9 copy from cyberduck worked after correct tcp setting. Were there any changes regarding memory allocation that could lead to this problem? 
What we use for cyberduck is an direct irods connection not via webdav.

**Comment by trel** [comment]
I assume you mean you're running iRODS 4.2.10.

There was minimal change from 4.2.9 to 4.2.10.

Cyberduck only does streaming (no parallel transfer) as far as I know.

@korydraughn Does this sound familiar?

**Comment by korydraughn** [comment]
That sounds right to me. I haven't seen any APIs in Jargon that support parallel transfer. In regards to the issue, I can't remember a time where I've encountered an error like that via Jargon.

**Comment by a-tsygan** [comment]
any ideas how to fix that? any similar cases that is not realted to Jargon? I
iRODS is getting stuck and requires restart. WebDav works fine, icommnds as well. But with WebDav on Windows we can not copy more then 4Gb it is way not enough. With Cyberduck we should be able transfer 100Gb but it is not working...

Here are some full logs.   
Sometimes we see that database plugin fails:
Aug 18 11:14:00 pid:11276 remote addresses: 129.125.36.212 ERROR: [-]	/irods/server/icat/src/icatHighLevelRoutines.cpp:131:int chlOpen() :  status [PLUGIN_ERROR]  errno [] -- message [failed to resolve database interface]
	[-]	/irods/server/core/src/irods_postgres_object.cpp:78:virtual irods::error irods::postgres_object::resolve(const std::string &, irods::plugin_ptr &) :  status [PLUGIN_ERROR]  errno [] -- message [Failed to load database plugin]
		[-]	/irods/server/core/src/irods_database_manager.cpp:94:irods::error irods::database_manager::init_from_type(const std::string &, const std::string &, const std::string &, const std::string &, irods::database_ptr &) :  status [PLUGIN_ERROR]  errno [] -- message [Failed to load database plugin]
			[-]	/irods/server/core/src/irods_database_manager.cpp:77:irods::error irods::database_manager::load_database_plugin(irods::database_ptr &, const std::string &, const std::string &, const std::string &) :  status [PLUGIN_ERROR]  errno [] -- message [failed to open shared object file [/usr/lib/irods/plugins/database/libpostgres.so] :: dlerror: is [/usr/lib/irods/plugins/database/libpostgres.so: failed to map segment from shared object: Cannot allocate memory]]
				[-]	/irods/lib/core/include/irods_load_plugin.hpp:176:irods::error irods::load_plugin(PluginType *&, const std::string &, const std::string &, const std::string &, const Ts &...) [PluginType = irods::database, Ts = <std::__1::basic_string<char>>] :  status [PLUGIN_ERROR]  errno [] -- message [failed to open shared object file [/usr/lib/irods/plugins/database/libpostgres.so] :: dlerror: is [/usr/lib/irods/plugins/database/libpostgres.so: failed to map segment from shared object: Cannot allocate memory]]

And here is the full log of the latest error (this time rule engine):
Caught signal [11]. Dumping stacktrace and exiting
Caught signal [Caught signal [1111]. Dumping stacktrace and exiting]. Dumping stacktrace and exiting


Dumping stack trace
<0>	Offset:       	Address: 0x7fb2d3261e03	/lib/libirods_server.so.4.2.10(+0xae0e03) [0x7fb2d3261e03]
<1>	Offset:       	Address: 0x7fb2d0d71630	/lib64/libpthread.so.0(+0xf630) [0x7fb2d0d71630]
<2>	Offset:       	Address: 0x7fb2c97676ea	/lib64/libpython2.7.so.1.0(PyObject_Malloc+0x28a) [0x7fb2c97676ea]
<3>	Offset:       	Address: 0x7fb2c97f27c9	/lib64/libpython2.7.so.1.0(_PyObject_GC_Malloc+0x19) [0x7fb2c97f27c9]
<4>	Offset:       	Address: 0x7fb2c97f2906	/lib64/libpython2.7.so.1.0(_PyObject_GC_NewVar+0x26) [0x7fb2c97f2906]
<5>	Offset:       	Address: 0x7fb2c977954f	/lib64/libpython2.7.so.1.0(PyTuple_New+0x7f) [0x7fb2c977954f]
<6>	Offset:       	Address: 0x7fb2c9784fa4	/lib64/libpython2.7.so.1.0(PyType_Ready+0x1f84) [0x7fb2c9784fa4]
<7>	Offset:       	Address: 0x7fb2c9784f58	/lib64/libpython2.7.so.1.0(PyType_Ready+0x1f38) [0x7fb2c9784f58]
<8>	Offset:       	Address: 0x7fb2c9766680	/lib64/libpython2.7.so.1.0(_Py_ReadyTypes+0x10) [0x7fb2c9766680]
<9>	Offset:       	Address: 0x7fb2c97e0686	/lib64/libpython2.7.so.1.0(Py_InitializeEx+0x76) [0x7fb2c97e0686]
<10>	Offset: 0x6a  	Address: 0x7fb2ca1dcf8a	start(std::__1::tuple<>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
<11>	Offset: 0x10  	Address: 0x7fb2ca229080	std::__1::__function::__func<irods::error (*)(std::__1::tuple<>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&), std::__1::allocator<irods::error (*)(std::__1::tuple<>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>, irods::error (std::__1::tuple<>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>::operator()(std::__1::tuple<>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
<12>	Offset: 0x8f  	Address: 0x7fb2d3299caf	irods::pluggable_rule_engine<std::__1::tuple<> >::start_operation(std::__1::tuple<>&)
<13>	Offset: 0x1060	Address: 0x7fb2d328f4b0	runIrodsAgentFactory(sockaddr_un)
<14>	Offset:       	Address: 0x42ce58	/usr/sbin/irodsServer(main+0x1708) [0x42ce58]
<15>	Offset:       	Address: 0x7fb2d09b6555	/lib64/libc.so.6(__libc_start_main+0xf5) [0x7fb2d09b6555]
<16>	Offset:       	Address: 0x42b56c	/usr/sbin/irodsServer() [0x42b56c]


Dumping stack trace
<0>	Offset:     	Address: 0x7fb2d3261e03	/lib/libirods_server.so.4.2.10(+0xae0e03) [0x7fb2d3261e03]
<1>	Offset:     	Address: 0x7fb2d0d71630	/lib64/libpthread.so.0(+0xf630) [0x7fb2d0d71630]
<2>	Offset:     	Address: 0x7fb2c97676ea	/lib64/libpython2.7.so.1.0(PyObject_Malloc+0x28a) [0x7fb2c97676ea]
<3>	Offset:     	Address: 0x7fb2c97703c2	/lib64/libpython2.7.so.1.0(PyString_FromStringAndSize+0xc2) [0x7fb2c97703c2]
<4>	Offset:     	Address: 0x7fb2c97d7958	/lib64/libpython2.7.so.1.0(+0xfa958) [0x7fb2c97d7958]
<5>	Offset:     	Address: 0x7fb2c97d7a6a	/lib64/libpython2.7.so.1.0(+0xfaa6a) [0x7fb2c97d7a6a]
<6>	Offset:     	Address: 0x7fb2c97d8193	/lib64/libpython2.7.so.1.0(+0xfb193) [0x7fb2c97d8193]
<7>	Offset:     	Address: 0x7fb2c97d7a6a	/lib64/libpython2.7.so.1.0(+0xfaa6a) [0x7fb2c97d7a6a]
<8>	Offset:     	Address: 0x7fb2c97d8166	/lib64/libpython2.7.so.1.0(+0xfb166) [0x7fb2c97d8166]
<9>	Offset:     	Address: 0x7fb2c97da078	/lib64/libpython2.7.so.1.0(PyMarshal_ReadObjectFromString+0x48) [0x7fb2c97da078]
<10>	Offset:     	Address: 0x7fb2c97da143	/lib64/libpython2.7.so.1.0(PyMarshal_ReadLastObjectFromFile+0x83) [0x7fb2c97da143]
<11>	Offset:     	Address: 0x7fb2c97d2ea1	/lib64/libpython2.7.so.1.0(+0xf5ea1) [0x7fb2c97d2ea1]
<12>	Offset:     	Address: 0x7fb2c97d476b	/lib64/libpython2.7.so.1.0(+0xf776b) [0x7fb2c97d476b]
<13>	Offset:     	Address: 0x7fb2c97d5451	/lib64/libpython2.7.so.1.0(+0xf8451) [0x7fb2c97d5451]
<14>	Offset:     	Address: 0x7fb2c97d569d	/lib64/libpython2.7.so.1.0(+0xf869d) [0x7fb2c97d569d]
<15>	Offset:     	Address: 0x7fb2c97d607e	/lib64/libpython2.7.so.1.0(PyImport_ImportModuleLevel+0x15e) [0x7fb2c97d607e]
<16>	Offset:     	Address: 0x7fb2c97b932f	/lib64/libpython2.7.so.1.0(+0xdc32f) [0x7fb2c97b932f]
<17>	Offset:     	Address: 0x7fb2c9729073	/lib64/libpython2.7.so.1.0(PyObject_Call+0x43) [0x7fb2c9729073]
<18>	Offset:     	Address: 0x7fb2c97baf07	/lib64/libpython2.7.so.1.0(PyEval_CallObjectWithKeywords+0x47) [0x7fb2c97baf07]
<19>	Offset:     	Address: 0x7fb2c97bfbc5	/lib64/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x46b5) [0x7fb2c97bfbc5]
<20>	Offset:     	Address: 0x7fb2c97c464d	/lib64/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7ed) [0x7fb2c97c464d]
<21>	Offset:     	Address: 0x7fb2c97c4752	/lib64/libpython2.7.so.1.0(PyEval_EvalCode+0x32) [0x7fb2c97c4752]
<22>	Offset:     	Address: 0x7fb2c97d453c	/lib64/libpython2.7.so.1.0(PyImport_ExecCodeModuleEx+0x8c) [0x7fb2c97d453c]
<23>	Offset:     	Address: 0x7fb2c97d47b8	/lib64/libpython2.7.so.1.0(+0xf77b8) [0x7fb2c97d47b8]
<24>	Offset:     	Address: 0x7fb2c97d5451	/lib64/libpython2.7.so.1.0(+0xf8451) [0x7fb2c97d5451]
<25>	Offset:     	Address: 0x7fb2c97d569d	/lib64/libpython2.7.so.1.0(+0xf869d) [0x7fb2c97d569d]
<26>	Offset:     	Address: 0x7fb2c97d607e	/lib64/libpython2.7.so.1.0(PyImport_ImportModuleLevel+0x15e) [0x7fb2c97d607e]
<27>	Offset:     	Address: 0x7fb2c97b932f	/lib64/libpython2.7.so.1.0(+0xdc32f) [0x7fb2c97b932f]
<28>	Offset:     	Address: 0x7fb2c9729073	/lib64/libpython2.7.so.1.0(PyObject_Call+0x43) [0x7fb2c9729073]
<29>	Offset:     	Address: 0x7fb2c97baf07	/lib64/libpython2.7.so.1.0(PyEval_CallObjectWithKeywords+0x47) [0x7fb2c97baf07]
<30>	Offset:     	Address: 0x7fb2c97bfbc5	/lib64/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x46b5) [0x7fb2c97bfbc5]
<31>	Offset:     	Address: 0x7fb2c97c464d	/lib64/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7ed) [0x7fb2c97c464d]
<32>	Offset:     	Address: 0x7fb2c97c4752	/lib64/libpython2.7.so.1.0(PyEval_EvalCode+0x32) [0x7fb2c97c4752]
<33>	Offset:     	Address: 0x7fb2c97d453c	/lib64/libpython2.7.so.1.0(PyImport_ExecCodeModuleEx+0x8c) [0x7fb2c97d453c]
<34>	Offset:     	Address: 0x7fb2c97d47b8	/lib64/libpython2.7.so.1.0(+0xf77b8) [0x7fb2c97d47b8]
<35>	Offset:     	Address: 0x7fb2c97d5451	/lib64/libpython2.7.so.1.0(+0xf8451) [0x7fb2c97d5451]
<36>	Offset:     	Address: 0x7fb2c97d569d	/lib64/libpython2.7.so.1.0(+0xf869d) [0x7fb2c97d569d]
<37>	Offset:     	Address: 0x7fb2c97d607e	/lib64/libpython2.7.so.1.0(PyImport_ImportModuleLevel+0x15e) [0x7fb2c97d607e]
<38>	Offset:     	Address: 0x7fb2c97b932f	/lib64/libpython2.7.so.1.0(+0xdc32f) [0x7fb2c97b932f]
<39>	Offset:     	Address: 0x7fb2c9729073	/lib64/libpython2.7.so.1.0(PyObject_Call+0x43) [0x7fb2c9729073]
<40>	Offset:     	Address: 0x7fb2c9729155	/lib64/libpython2.7.so.1.0(+0x4c155) [0x7fb2c9729155]
<41>	Offset:     	Address: 0x7fb2c972923e	/lib64/libpython2.7.so.1.0(PyObject_CallFunction+0x8e) [0x7fb2c972923e]
<42>	Offset:     	Address: 0x7fb2c97d6b22	/lib64/libpython2.7.so.1.0(PyImport_Import+0x112) [0x7fb2c97d6b22]
<43>	Offset:     	Address: 0x7fb2c97d6c9a	/lib64/libpython2.7.so.1.0(PyImport_ImportModule+0x1a) [0x7fb2c97d6c9a]
<44>	Offset:     	Address: 0x7fb2c97df940	/lib64/libpython2.7.so.1.0(+0x102940) [0x7fb2c97df940]
<45>	Offset:     	Address: 0x7fb2c97e0c5d	/lib64/libpython2.7.so.1.0(Py_InitializeEx+0x64d) [0x7fb2c97e0c5d]
<46>	Offset: 0x6a	Address: 0x7fb2ca1dcf8a	start(std::__1::tuple<>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
<47>	Offset: 0x10	Address: 0x7fb2ca229080	std::__1::__function::__func<irods::error (*)(std::__1::tuple<>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&), std::__1::allocator<irods::error (*)(std::__1::tuple<>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>, irods::error (std::__1::tuple<>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>::operator()(std::__1::tuple<>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
<48>	Offset: 0x8f	Address: 0x7fb2d3299caf	irods::pluggable_rule_engine<std::__1::tuple<> >::start_operation(std::__1::tuple<>&)


Dumping stack trace
<0>	Offset:     	Address: 0x7fb2d3261e03	/lib/libirods_server.so.4.2.10(+0xae0e03) [0x7fb2d3261e03]
<1>	Offset:     	Address: 0x7fb2d0d71630	/lib64/libpthread.so.0(+0xf630) [0x7fb2d0d71630]
<2>	Offset:     	Address: 0x7fb2c97676ea	/lib64/libpython2.7.so.1.0(PyObject_Malloc+0x28a) [0x7fb2c97676ea]
<3>	Offset:     	Address: 0x7fb2c97703c2	/lib64/libpython2.7.so.1.0(PyString_FromStringAndSize+0xc2) [0x7fb2c97703c2]
<4>	Offset:     	Address: 0x7fb2c97d7958	/lib64/libpython2.7.so.1.0(+0xfa958) [0x7fb2c97d7958]
<5>	Offset:     	Address: 0x7fb2c97d7a6a	/lib64/libpython2.7.so.1.0(+0xfaa6a) [0x7fb2c97d7a6a]
<6>	Offset:     	Address: 0x7fb2c97d8193	/lib64/libpython2.7.so.1.0(+0xfb193) [0x7fb2c97d8193]
<7>	Offset:     	Address: 0x7fb2c97d7a6a	/lib64/libpython2.7.so.1.0(+0xfaa6a) [0x7fb2c97d7a6a]
<8>	Offset:     	Address: 0x7fb2c97d8166	/lib64/libpython2.7.so.1.0(+0xfb166) [0x7fb2c97d8166]
<9>	Offset:     	Address: 0x7fb2c97da078	/lib64/libpython2.7.so.1.0(PyMarshal_ReadObjectFromString+0x48) [0x7fb2c97da078]
<10>	Offset:     	Address: 0x7fb2c97da143	/lib64/libpython2.7.so.1.0(PyMarshal_ReadLastObjectFromFile+0x83) [0x7fb2c97da143]
<11>	Offset:     	Address: 0x7fb2c97d2ea1	/lib64/libpython2.7.so.1.0(+0xf5ea1) [0x7fb2c97d2ea1]
<12>	Offset:     	Address: 0x7fb2c97d476b	/lib64/libpython2.7.so.1.0(+0xf776b) [0x7fb2c97d476b]
<13>	Offset:     	Address: 0x7fb2c97d5451	/lib64/libpython2.7.so.1.0(+0xf8451) [0x7fb2c97d5451]
<14>	Offset:     	Address: 0x7fb2c97d569d	/lib64/libpython2.7.so.1.0(+0xf869d) [0x7fb2c97d569d]
<15>	Offset:     	Address: 0x7fb2c97d607e	/lib64/libpython2.7.so.1.0(PyImport_ImportModuleLevel+0x15e) [0x7fb2c97d607e]
<16>	Offset:     	Address: 0x7fb2c97b932f	/lib64/libpython2.7.so.1.0(+0xdc32f) [0x7fb2c97b932f]
<17>	Offset:     	Address: 0x7fb2c9729073	/lib64/libpython2.7.so.1.0(PyObject_Call+0x43) [0x7fb2c9729073]
<18>	Offset:     	Address: 0x7fb2c97baf07	/lib64/libpython2.7.so.1.0(PyEval_CallObjectWithKeywords+0x47) [0x7fb2c97baf07]
<19>	Offset:     	Address: 0x7fb2c97bfbc5	/lib64/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x46b5) [0x7fb2c97bfbc5]
<20>	Offset:     	Address: 0x7fb2c97c464d	/lib64/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7ed) [0x7fb2c97c464d]
<21>	Offset:     	Address: 0x7fb2c97c4752	/lib64/libpython2.7.so.1.0(PyEval_EvalCode+0x32) [0x7fb2c97c4752]
<22>	Offset:     	Address: 0x7fb2c97d453c	/lib64/libpython2.7.so.1.0(PyImport_ExecCodeModuleEx+0x8c) [0x7fb2c97d453c]
<23>	Offset:     	Address: 0x7fb2c97d47b8	/lib64/libpython2.7.so.1.0(+0xf77b8) [0x7fb2c97d47b8]
<24>	Offset:     	Address: 0x7fb2c97d5451	/lib64/libpython2.7.so.1.0(+0xf8451) [0x7fb2c97d5451]
<25>	Offset:     	Address: 0x7fb2c97d569d	/lib64/libpython2.7.so.1.0(+0xf869d) [0x7fb2c97d569d]
<26>	Offset:     	Address: 0x7fb2c97d607e	/lib64/libpython2.7.so.1.0(PyImport_ImportModuleLevel+0x15e) [0x7fb2c97d607e]
<27>	Offset:     	Address: 0x7fb2c97b932f	/lib64/libpython2.7.so.1.0(+0xdc32f) [0x7fb2c97b932f]
<28>	Offset:     	Address: 0x7fb2c9729073	/lib64/libpython2.7.so.1.0(PyObject_Call+0x43) [0x7fb2c9729073]
<29>	Offset:     	Address: 0x7fb2c97baf07	/lib64/libpython2.7.so.1.0(PyEval_CallObjectWithKeywords+0x47) [0x7fb2c97baf07]
<30>	Offset:     	Address: 0x7fb2c97bfbc5	/lib64/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x46b5) [0x7fb2c97bfbc5]
<31>	Offset:     	Address: 0x7fb2c97c464d	/lib64/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7ed) [0x7fb2c97c464d]
<32>	Offset:     	Address: 0x7fb2c97c4752	/lib64/libpython2.7.so.1.0(PyEval_EvalCode+0x32) [0x7fb2c97c4752]
<33>	Offset:     	Address: 0x7fb2c97d453c	/lib64/libpython2.7.so.1.0(PyImport_ExecCodeModuleEx+0x8c) [0x7fb2c97d453c]
<34>	Offset:     	Address: 0x7fb2c97d47b8	/lib64/libpython2.7.so.1.0(+0xf77b8) [0x7fb2c97d47b8]
<35>	Offset:     	Address: 0x7fb2c97d5451	/lib64/libpython2.7.so.1.0(+0xf8451) [0x7fb2c97d5451]
<36>	Offset:     	Address: 0x7fb2c97d569d	/lib64/libpython2.7.so.1.0(+0xf869d) [0x7fb2c97d569d]
<37>	Offset:     	Address: 0x7fb2c97d607e	/lib64/libpython2.7.so.1.0(PyImport_ImportModuleLevel+0x15e) [0x7fb2c97d607e]
<38>	Offset:     	Address: 0x7fb2c97b932f	/lib64/libpython2.7.so.1.0(+0xdc32f) [0x7fb2c97b932f]
<39>	Offset:     	Address: 0x7fb2c9729073	/lib64/libpython2.7.so.1.0(PyObject_Call+0x43) [0x7fb2c9729073]
<40>	Offset:     	Address: 0x7fb2c9729155	/lib64/libpython2.7.so.1.0(+0x4c155) [0x7fb2c9729155]
<41>	Offset:     	Address: 0x7fb2c972923e	/lib64/libpython2.7.so.1.0(PyObject_CallFunction+0x8e) [0x7fb2c972923e]
<42>	Offset:     	Address: 0x7fb2c97d6b22	/lib64/libpython2.7.so.1.0(PyImport_Import+0x112) [0x7fb2c97d6b22]
<43>	Offset:     	Address: 0x7fb2c97d6c9a	/lib64/libpython2.7.so.1.0(PyImport_ImportModule+0x1a) [0x7fb2c97d6c9a]
<44>	Offset:     	Address: 0x7fb2c97df940	/lib64/libpython2.7.so.1.0(+0x102940) [0x7fb2c97df940]
<45>	Offset:     	Address: 0x7fb2c97e0c5d	/lib64/libpython2.7.so.1.0(Py_InitializeEx+0x64d) [0x7fb2c97e0c5d]
<46>	Offset: 0x6a	Address: 0x7fb2ca1dcf8a	start(std::__1::tuple<>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
<47>	Offset: 0x10	Address: 0x7fb2ca229080	std::__1::__function::__func<irods::error (*)(std::__1::tuple<>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&), std::__1::allocator<irods::error (*)(std::__1::tuple<>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>, irods::error (std::__1::tuple<>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>::operator()(std::__1::tuple<>&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
<48>	Offset: 0x8f	Address: 0x7fb2d3299caf	irods::pluggable_rule_engine<std::__1::tuple<> >::start_operation(std::__1::tuple<>&)

Aug 19 12:38:51 pid:10179  ERROR: Agent process [15497] exited with status [11]
Aug 19 12:38:51 pid:10179  ERROR: Agent process [15501] exited with status [11]
Aug 19 12:38:51 pid:10179  ERROR: Agent process [15514] exited with status [11]
Aug 19 12:39:27 pid:10179  ERROR: fork() failed in rodsAgent process factory
Aug 19 12:41:01 pid:15560  ERROR: [-]	/irods/server/re/include/irods_re_plugin.hpp:362:irods::error irods::rule_engine_plugin_manager<std::__1::tuple<> >::resolve(std::string &, const std::string &, pluggable_rule_engine<T> *&) [T = std::__1::tuple<>] :  status [PLUGIN_ERROR]  errno [] -- message [failed to open shared object file [/usr/lib/irods/plugins/rule_engines/libirods_rule_engine_plugin-python.so] :: dlerror: is [/usr/lib/irods/plugins/rule_engines/libirods_rule_engine_plugin-python.so: failed to map segment from shared object: Cannot allocate memory]]
	[-]	/irods/lib/core/include/irods_load_plugin.hpp:176:irods::error irods::load_plugin(PluginType *&, const std::string &, const std::string &, const std::string &, const Ts &...) [PluginType = irods::pluggable_rule_engine<std::__1::tuple<> >, Ts = <std::__1::basic_string<char>>] :  status [PLUGIN_ERROR]  errno [] -- message [failed to open shared object file [/usr/lib/irods/plugins/rule_engines/libirods_rule_engine_plugin-python.so] :: dlerror: is [/usr/lib/irods/plugins/rule_engines/libirods_rule_engine_plugin-python.so: failed to map segment from shared object: Cannot allocate memory]]

Aug 19 12:41:01 pid:15560  ERROR: [-]	/irods/server/re/include/irods_re_plugin.hpp:387:auto irods::rule_engine_manager<std::__1::tuple<>, RuleExecInfo *>::rule_engine_manager(rule_engine_plugin_manager<std::__1::tuple<> > &, std::vector<re_pack_inp<tuple<> > > &, microservice_manager<RuleExecInfo *> &)::(anonymous class)::operator()(re_pack_inp<T> &) const [T = std::__1::tuple<>, C = RuleExecInfo *] :  status [PLUGIN_ERROR]  errno [] -- message [failed to open shared object file [/usr/lib/irods/plugins/rule_engines/libirods_rule_engine_plugin-python.so] :: dlerror: is [/usr/lib/irods/plugins/rule_engines/libirods_rule_engine_plugin-python.so: failed to map segment from shared object: Cannot allocate memory]]
	[-]	/irods/server/re/include/irods_re_plugin.hpp:401:irods::error irods::rule_engine_manager<std::__1::tuple<>, RuleExecInfo *>::init_rule_engine(re_pack_inp<T> &) [T = std::__1::tuple<>, C = RuleExecInfo *] :  status [PLUGIN_ERROR]  errno [] -- message [failed to open shared object file [/usr/lib/irods/plugins/rule_engines/libirods_rule_engine_plugin-python.so] :: dlerror: is [/usr/lib/irods/plugins/rule_engines/libirods_rule_engine_plugin-python.so: failed to map segment from shared object: Cannot allocate memory]]
		[-]	/irods/lib/core/include/irods_load_plugin.hpp:176:irods::error irods::load_plugin(PluginType *&, const std::string &, const std::string &, const std::string &, const Ts &...) [PluginType = irods::pluggable_rule_engine<std::__1::tuple<> >, Ts = <std::__1::basic_string<char>>] :  status [PLUGIN_ERROR]  errno [] -- message [failed to open shared object file [/usr/lib/irods/plugins/rule_engines/libirods_rule_engine_plugin-python.so] :: dlerror: is [/usr/lib/irods/plugins/rule_engines/libirods_rule_engine_plugin-python.so: failed to map segment from shared object: Cannot allocate memory]]

Aug 19 12:41:03 pid:15560  ERROR: [-]	/irods/server/re/include/irods_re_plugin.hpp:362:irods::error irods::rule_engine_plugin_manager<std::__1::tuple<> >::resolve(std::string &, const std::string &, pluggable_rule_engine<T> *&) [T = std::__1::tuple<>] :  status [PLUGIN_ERROR]  errno [] -- message [failed to open shared object file [/usr/lib/irods/plugins/rule_engines/libirods_rule_engine_plugin-cpp_default_policy.so] :: dlerror: is [/usr/lib/irods/plugins/rule_engines/libirods_rule_engine_plugin-cpp_default_policy.so: failed to map segment from shared object: Cannot allocate memory]]
	[-]	/irods/lib/core/include/irods_load_plugin.hpp:176:irods::error irods::load_plugin(PluginType *&, const std::string &, const std::string &, const std::string &, const Ts &...) [PluginType = irods::pluggable_rule_engine<std::__1::tuple<> >, Ts = <std::__1::basic_string<char>>] :  status [PLUGIN_ERROR]  errno [] -- message [failed to open shared object file [/usr/lib/irods/plugins/rule_engines/libirods_rule_engine_plugin-cpp_default_policy.so] :: dlerror: is [/usr/lib/irods/plugins/rule_engines/libirods_rule_engine_plugin-cpp_default_policy.so: failed to map segment from shared object: Cannot allocate memory]]

Aug 19 12:41:04 pid:15560  ERROR: [-]	/irods/server/re/include/irods_re_plugin.hpp:387:auto irods::rule_engine_manager<std::__1::tuple<>, RuleExecInfo *>::rule_engine_manager(rule_engine_plugin_manager<std::__1::tuple<> > &, std::vector<re_pack_inp<tuple<> > > &, microservice_manager<RuleExecInfo *> &)::(anonymous class)::operator()(re_pack_inp<T> &) const [T = std::__1::tuple<>, C = RuleExecInfo *] :  status [PLUGIN_ERROR]  errno [] -- message [failed to open shared object file [/usr/lib/irods/plugins/rule_engines/libirods_rule_engine_plugin-cpp_default_policy.so] :: dlerror: is [/usr/lib/irods/plugins/rule_engines/libirods_rule_engine_plugin-cpp_default_policy.so: failed to map segment from shared object: Cannot allocate memory]]
	[-]	/irods/server/re/include/irods_re_plugin.hpp:401:irods::error irods::rule_engine_manager<std::__1::tuple<>, RuleExecInfo *>::init_rule_engine(re_pack_inp<T> &) [T = std::__1::tuple<>, C = RuleExecInfo *] :  status [PLUGIN_ERROR]  errno [] -- message [failed to open shared object file [/usr/lib/irods/plugins/rule_engines/libirods_rule_engine_plugin-cpp_default_policy.so] :: dlerror: is [/usr/lib/irods/plugins/rule_engines/libirods_rule_engine_plugin-cpp_default_policy.so: failed to map segment from shared object: Cannot allocate memory]]
		[-]	/irods/lib/core/include/irods_load_plugin.hpp:176:irods::error irods::load_plugin(PluginType *&, const std::string &, const std::string &, const std::string &, const Ts &...) [PluginType = irods::pluggable_rule_engine<std::__1::tuple<> >, Ts = <std::__1::basic_string<char>>] :  status [PLUGIN_ERROR]  errno [] -- message [failed to open shared object file [/usr/lib/irods/plugins/rule_engines/libirods_rule_engine_plugin-cpp_default_policy.so] :: dlerror: is [/usr/lib/irods/plugins/rule_engines/libirods_rule_engine_plugin-cpp_default_policy.so: failed to map segment from shared object: Cannot allocate memory]]

Aug 19 12:41:24 pid:15560  ERROR: cllConnect: SQLConnect failed: -1
Aug 19 12:41:24 pid:15560  ERROR: cllConnect: SQLConnect failed:odbcEntry=iRODS Catalog,user=irods,pass=XXXXX
Aug 19 12:41:24 pid:15560  ERROR: cllConnect:          SQLSTATE: IM002
Aug 19 12:41:24 pid:15560  ERROR: cllConnect:  Native Error Code: 0
Aug 19 12:41:24 pid:15560  ERROR: cllConnect: [unixODBC][Driver Manager]Data source name not found, and no default driver specified 
Aug 19 12:41:24 pid:15560 NOTICE: _rsGenQuery: genQuery status = -824000
Aug 19 12:41:24 pid:15560 NOTICE: rsGenQuery: _rsGenQuery failed, status = -824000
Aug 19 12:41:24 pid:15560 NOTICE: initZone: rsGenQuery error, status = -824000
Aug 19 12:41:24 pid:15560 SYSTEM FATAL: initServerInfo: initZone error, status = -824000
Aug 19 12:41:24 pid:15560  ERROR: initAgent: initServerInfo error, status = -824000
Aug 19 12:41:24 pid:15560  ERROR: agentMain :: initAgent failed: -824000
Aug 19 12:41:24 pid:15560  ERROR: cllDisconnect: SQLDisconnect failed: -2
Aug 19 12:41:24 pid:15560 NOTICE: initInfoWithRcat: chlClose Error. Status = -804000

**Comment by korydraughn** [comment]
The log says `Cannot allocate memory`. How much memory is available to the machine?

Is the database configuration defined in server_config.json?

**Comment by a-tsygan** [comment]
Yes, the iRODS configuration is pretty standard. On this test server we do not have much memory and no swap configured. 
However, the copy process from cyberduck  fails approximately  after ~500Mb was copied. More over after process fails irods reports ~500Mb size of a file. 500Mb is way less then the the total memory (on test server we have 8G) but I would be very surprised if for push data into the storage irods needs to buffer so much data.
Our PostgreSQL dba reports that there are no errors on the databases side. 
On the server side we have default and probably wrong shmmax parameter value. I suspect that this might influence maloc function call but I have no idea if this might lead to a problem or not. 
For instance looking into this code 
https://github.com/irods/irods/blob/master/plugins/rule_engines/irods_rule_engine_plugin-irods_rule_language/cache.cpp
I see that shmmax value is a key thing but there is no documentation what is the recommended value

**Comment by trel** [comment]
Are we falling victim to how the client calls our API?   In this case, Cyberduck?

**Comment by a-tsygan** [comment]
maybe. But error happens on the server side. My main concern is that it worked before upgrade. I can not say exactly if we were testing on 4.2.8 or 4.2.9 before. It might be that our first tests were done on  4.2.8.
Were there any changes from 4.2.8 to 4.2.9 that could influence this use case?
Maybe you can test if you can reproduce the error on cyberduck with irods cyberduckprofile while copy ~20G file into the iRODS?

**Comment by kript** [comment]
> On the server side we have default and probably wrong shmmax parameter value. I suspect that this might influence maloc function call but I have no idea if this might lead to a problem or not.
> For instance looking into this code
> https://github.com/irods/irods/blob/master/plugins/rule_engines/irods_rule_engine_plugin-irods_rule_language/cache.cpp
> I see that shmmax value is a key thing but there is no documentation what is the recommended value
> 
> However reading from this code:
> https://github.com/irods/irods/blob/master/server/re/include/sharedmemory.hpp
> #define SHMMAX 30000000
> I start to think that server shmmax setting does not matter for iRODS...

We have seen issues around this, and haven't got an good shmax value yet either. I do find that we need to bump it on the Docker side (see #4675 and https://github.com/irods/irods_demo/pull/23 )

**Comment by kript** [comment]
> any ideas how to fix that? any similar cases that is not related to Jargon? I
> iRODS is getting stuck and requires restart. WebDav works fine, icommands as well. But with WebDav on Windows we can not copy more than 4Gb it is way not enough. With Cyberduck we should be able transfer 100Gb but it is not working...

Have you come across Utrecht Uni's [YodaDrive](https://github.com/UtrechtUniversity/YodaDrive) which works around a similar problem as [discussed on the irods-chat list](https://groups.google.com/g/irod-chat/c/h4wsiRBItC8/m/AcIF57FVCQAJ)?

**Comment by kript** [comment]
> > On the server side we have default and probably wrong shmmax parameter value. I suspect that this might influence maloc function call but I have no idea if this might lead to a problem or not.
> > For instance looking into this code
> > https://github.com/irods/irods/blob/master/plugins/rule_engines/irods_rule_engine_plugin-irods_rule_language/cache.cpp
> > I see that shmmax value is a key thing but there is no documentation what is the recommended value
> > However reading from this code:
> > https://github.com/irods/irods/blob/master/server/re/include/sharedmemory.hpp
> > #define SHMMAX 30000000
> > I start to think that server shmmax setting does not matter for iRODS...
> 
> We have seen issues around this, and haven't got an good shmax value yet either. I do find that we need to bump it on the Docker side (see #4675 and [irods/irods_demo#23](https://github.com/irods/irods_demo/pull/23) )

sorry, I should be clearer; we have seen shmax errors but have not linked it to a particular operation/area.

**Comment by a-tsygan** [comment]
I think I've found the problem by excluding parts of a system one by one. I suspect that problem is somhowe related to the audit plugin configuration (i need to check with team members that taking care about that part). My guess is that something is triggered when java writes and that "something" kills the memory with time and blocks all iRODS functions. At least after I've turned that part off - thing went back to norm and passed magic 500Gb point and closing up to 1G. I'll post here more details after I'll collect more information.

**Comment by trel** [comment]
Ah, so the individual file part writes... each trigger a message sent (or 5 or 10) and that somehow exhausts the system memory.

Very interesting.

**Comment by a-tsygan** [comment]
So fare I think audit plugin is the core of our current problem.
It looks like that there is not properly closed connection or that too many objects are in the memory.   
I think that potential problem might be in this code:
https://github.com/irods/irods_rule_engine_plugin_audit_amqp/blob/master/packaging/queue_listener.py
    def run(self):
        timeout = 5
        num_workers = 5

Is it possible that with intensive write the message queue grows uncontrollable and timeout=5 is slowing events processing, thus leading to the memory overflow? (queue grows faster then processed during too long time)
If it is the case, then indeed swap might help, but only till it is also full. And from the error we see at the moment it takes ~500Mb to kill system with 8Gb of ram even with the upload speed < 1Mb/s

**Comment by Venustiano** [comment]
A screenshot of kibana shows that the problematic peps being triggered during the file transfer are audit_pep_api_data_obj_write_post/pre. Filtering these peps in the server can be a workaround but a **proper fix is needed**.

![image](https://user-images.githubusercontent.com/39260912/130470118-f6434359-2491-4ff9-8077-e3052a67e40c.png)

**Comment by a-tsygan** [comment]
At the moment we've added filtering to server_config.json to exclude **data_obj_write** events
            {
                "instance_name":"irods_rule_engine_plugin-audit_amqp-instance"
                ,"plugin_name":"irods_rule_engine_plugin-audit_amqp"
                ,"plugin_specific_configuration": 
                { 
                    "pep_regex_to_match": "(^audit_pep_api_((?!gen_query|auth_response|auth_request|**data_obj_write**).)*_(pre|post)$|audit_pep_api_auth_.*_except)"
                    ,"amqp_topic": "audit_messages"
                    ,"amqp_location": "<host>:<port>"
                    ,"amqp_options": ""
                }
            },

**Comment by trel** [comment]
Good sleuthing (and clean workaround).

So far, this just sounds like resource exhaustion... we'll keep thinking about what we can do about this in the server or in the pugin.

That buf appears to be all zeros?  Is that surprising?

**Comment by trel** [comment]
The code in `queue_listener.py` is only used in the test framework so we don't have to stand up a full AMQP/Elastic stack to make sure the plugin is doing its job correctly.   It doesn't run in a real deployment.

**Comment by a-tsygan** [comment]
All zeros that you see is correct. It is a test 1Gb file which is generated using mkfile command on mac. That tool generates files that contains only 0.
queue_listener.py: ok, it was just a blind guess. But it is sounds like events queue needs to go to the database and pop from there otherwise we are always at risk on memory overflow in pike load. 
Also in this case it is good to know memory prerequisite per-server.  
And does it mean that we need to take into account  audit plugin configuration on each resource?
( we've detected problems only on the main server and not on the resources).

**Comment by trel** [comment]
Yes, this will be in play on all servers running the audit plugin and doing the writing to the storage.

**Comment by a-tsygan** [comment]
Maybe it is good to add audit plugin configuration settings. 
1. performance: like it is now with the risk of "out of memory"
2. stable: trade some performance but put processes on hold when message queue grows to the some configurable limit and wait till all messages or part of the messages (probably configurable as well) is fully processed and cleaned out

**Comment by bh9** [comment]
Is this potentially related to the issue we've seen with the indexing plugin? Where the creation of delayed rule executions outpaces the processing of them, so they pile up, each taking up some memory until the host's memory is exhausted

**Comment by trel** [comment]
I don't think this is related to the indexing plugin (which uses the delay server)... the audit plugin sends its AMQP messages directly, synchronously.

The problematic PEPs indicated above (`audit_pep_api_data_obj_write_(pre|post)`) send the entire content of the files being written in their `buf` (by design).

I think the action item here is documentation only for the audit plugin - settings, expectations, best practices.

**Comment by trel** [comment]
I think this can be closed, since https://github.com/irods/irods_rule_engine_plugin_audit_amqp/issues/61 was fixed for 4.2.11.0 by not sending the `buf` to AMQP.   There should no longer be resource exhaustion, regardless of the client (cyberduck, or otherwise).

**Comment by alanking** [comment]
Sounds like this is better now. Please open a new issue if problems persist.
